version: '3'
services:
  db:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    platform: linux/amd64
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 13316:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
