name: Get back migrations hash

inputs:
  ref: branch
outputs:
  hash:
    value: ${{ steps.set-hash.outputs.hash }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ref
        fetch-depth: 0

    - name: back migrations hash
      id: set-hash
      shell: bash
      run: |
        echo "hash=$(git log -n 1 --pretty=format:"%h" -- back/db/migrations)" >> $GITHUB_OUTPUT
