name: Get back migrations hash

outputs:
  hash:
    value: ${{ steps.set-hash.outputs.hash }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: echo ${GITHUB_REF#refs/heads/}
        fetch-depth: 0

    - run: echo ${GITHUB_REF#refs/heads/}
      shell: bash

    - name: back migrations hash
      id: set-hash
      shell: bash
      run: |
        echo "hash=$(git log -n 1 --pretty=format:"%h" -- back/db/migrations)" >> $GITHUB_OUTPUT
