/* tslint:disable */
/* eslint-disable */
/**
 * Fastify todo api
 * Fastify todo api Swagger
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthSignUpPost200Response
 */
export interface AuthSignUpPost200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthSignUpPost200Response
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignUpPost200Response
     */
    'name'?: string;
}

