name: CI

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  prepare-db:
    name: Prepare DB
    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: fastify_todo
      MYSQL_ROOT_PASSWORD: password
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.28
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
        volumes:
          - mysql-data:/var/lib/mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Typeorm
        run: |
          yarn workspace back createDatabase
          yarn workspace back migration:run

  backend-test:
    needs: prepare-db
    name: Backend Test
    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: fastify_todo
      MYSQL_ROOT_PASSWORD: password
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.28
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
        volumes:
          - mysql-data:/var/lib/mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Run test
        id: run-test
        run: yarn workspace back test
